name: Create Issue on Workflow Failure

on:
  workflow_run:
    workflows: ["Decide-Lorca application"]
    types: [completed]

jobs:
  create-issue-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}

    steps:
      - name: Create Issue on Workflow Failure
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

        run: |
          issue_title="Error in CI ${{ github.event.workflow.name }} - Decide"
          issue_body="The workflow '${{ github.event.workflow.name }}' has failed and the PR cannot be merged. Don't forget to add the group label and assign an assignee."

          # Determinar la etiqueta basada en el GitHub.actor
          if [[ "${{ github.actor }}" == "alblopnov" || "${{ github.actor }}" == "alejandromd" || "${{ github.actor }}" == "davdelpal1" || "${{ github.actor }}" == "goncammej" || "${{ github.actor }}" == "JuanAntonioJimenezdelVillar" || "${{ github.actor }}" == "Thealean28" ]]; then
              labels='"labels": ["Error", "Medium", "lorca-1"]'
          elif [[ "${{ github.actor }}" == "alvarobernal2412" || "${{ github.actor }}" == "josgarber6" || "${{ github.actor }}" == "alvgonfri" || "${{ github.actor }}" == "mangarrui" || "${{ github.actor }}" == "jmartinacu" || "${{ github.actor }}" == "sebasruii" ]]; then
              labels='"labels": ["Error", "Medium", "lorca-2"]'
          else
              labels='"labels": ["Error", "Medium"]'
          fi

          issue_number=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{'"$labels"', "title": "'"$issue_title"'", "body": "'"$issue_body"'", "assignees": ["'${{ github.actor }}'"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues" | jq '.number')
