name: Create Issue on Workflow Failure

on:
  workflow_run:
    workflows: ["Decide-Lorca application"]
    types: [completed]

jobs:
  create-issue-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}

    steps:
      - name: Create Issue on Workflow Failure
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

        run: |
          # Título y cuerpo de la issue
          issue_title="Error in CI ${{ github.event.workflow.name }} - Decide"
          issue_body="The workflow '${{ github.event.workflow.name }}' has failed and the PR cannot be merged. Don't forget to add the group label and assign an assignee."

          # Agregar las etiquetas al cuerpo del JSON
          labels='"labels": ["Error", "Medium"]'

          # Obtener el usuario que activó el flujo de trabajo
          user_login=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs" | jq -r '.workflow_runs[] | select(.id == '${{ github.event.workflow_run.id }}') | .head_commit.author.login')

          # Crear la issue utilizando la API de GitHub y asignarla al usuario que activó el flujo de trabajo
          issue_number=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{'"$labels"', "title": "'"$issue_title"'", "body": "'"$issue_body"'", "assignees": ["'"$user_login"'"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues" | jq '.number')
