name: Create Issue on Workflow Failure

on:
  workflow_run:
    workflows: ["Decide-Lorca application"]
    types: [completed]

jobs:
  create-issue-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}

    steps:
      - name: Create Issue on Workflow Failure
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

        run: |
          # Título y cuerpo de la issue
          issue_title="Error in CI (${{ github.event.workflow.name }} - Decide )"
          issue_body="The workflow '${{ github.event.workflow.name }}' has failed in the main branch."

          # Agregar las etiquetas al cuerpo del JSON
          labels='"labels": ["Error", "Medium"], '

          # Crear la issue utilizando la API de GitHub
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{'"$labels"' "title": "'"$issue_title"'", "body": "'"$issue_body"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues"
