name: Create Issue on Test Failure

on:
  workflow_run:
    workflows: ["Decide-Lorca application"]
    types:
      - completed

jobs:
  create-issue-on-failure:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Check test status
        run: |
          if [ ${{ needs.run-tests.outputs.tests_failed }} -ne 0 ]; then
            echo "Tests failed, creating issue"
            node CI-Testing/.github/scripts/create_issue.js
          else
            echo "All tests passed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
